### ISSUE TITLE
German, Switzerland

### ISSUE THREAD

**Issue by nickw108** [magento-l10n/i18n-magento2#6]
I'm currently maintaining de_CH (German/Switzerland) on https://github.com/openstream/Magento2_German_LocalePack_de_CH, which is forked from https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE, because there are only some nuances in written German in Switzerland. Also the formatting e.g. for decimal numbers, which is why it's important that there's a separate locale for de_CH.

How will it be possible to avoid a lot of unnecessary manual work on crowdin.com duplicating translation strings? I saw your commits in this repository, so it looks like you're exporting from crowdin and then committing here on Github. Maybe there's a way how we can reuse the existing German and Swiss German translations without days or even weeks of copy/pasting?

**Comment by vkublytskyi** [comment]
I don't see any possibility to say that locale A extends locale B. But I think that may be handled by our packaging tool. So language package for de_CH will be built from both de_DE and de_CH source code. This is what goes to mind at first. But maybe there is a better approach.

Now, if you don't mind, I will take translations from https://github.com/openstream/Magento2_German_LocalePack_de_CH to upload initial content to https://crowdin.com/project/magento-2/de-CH.

**Comment by nickw108** [comment]
Let me sync from upstream (de_DE) first, then you're welcome to take those contents for the initial upload. I read that you plan to develop tools allowing community members to contribute translations directly from GitHub. I think that would be the best for de_CH. 

Not sure what the de_DE contributors think about Crowdin, maybe we can discuss this at some point.

**Comment by vkublytskyi** [comment]
Translations uploaded to Crowdin.
